version: 2
project_name: sensu-check-entropy

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/check-entropy/main.go
    id: check-entropy
    binary: bin/check-entropy
    env:
      - CGO_ENABLED=0
    targets:
      - linux_386
      - linux_amd64
      - linux_arm_7
      - linux_arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - main: ./cmd/metrics-entropy/main.go
    id: metrics-entropy
    binary: bin/metrics-entropy
    env:
      - CGO_ENABLED=0
    targets:
      - linux_386
      - linux_amd64
      - linux_arm_7
      - linux_arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: tar
    formats: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

